import 'dart:developer';

import 'package:cloud_firestore/cloud_firestore.dart';

class FirestoreService {
  final _db = FirebaseFirestore.instance;

  // create list(collection)
  Future<void> createList({
    required String listName,
    required String ownerId,
    String? note,
  }) async {
    await _db.collection('lists').add({
      'name': listName,
      'ownerId': ownerId,
      'members': [ownerId],
      'createdAt': FieldValue.serverTimestamp(),
      'note': note,
    });
  }

  // add item(subcollection of the listId)
  Future<void> addItem({
    required String listId,
    required String itemName,
    required String addedBy,
  }) async {
    await _db
        .collection('lists')
        .doc(listId)
        .collection('items')
        .add({
          'name': itemName,
          'done': false,
          'addedBy': addedBy,
          'createdAt': FieldValue.serverTimestamp(),
        });
  }

  // ! still working on it
  // invite people by listId
  Future<void> inviteUser({
    required String listId,
    required String userId,
  }) async {
    final listRef = _db.collection('lists').doc(listId);
    await listRef.update({
      'members': FieldValue.arrayUnion([userId]),
    });
  }

  // to see docs names(generated by firebase)
  printDocumentsId() async {
    // final docs = _db.collection('lists').doc();

    final docs = await _db.collection('lists').get();

    for (var doc in docs.docs) {
      log(doc.id.toString());
    }
  }
}


  // getDocument({
  //   required String collectionName,
  //   required String documentName,
  // }) async {
  //   try {
  //     final doc = await _db.collection(collectionName).doc(documentName).get();

  //     // to see if document added right
  //     if (doc.exists) {
  //       log('Document data: ${doc.data()}');
  //     } else {
  //       log('No document found with ID $documentName');
  //     }
  //     return doc;
  //   } catch (e) {
  //     log(e.toString());
  //   }
  // }

  // create collection(List) and add document(item) beacuse it is requied
  // addCollection({required String collectionName, String? note}) async {
  //   await _db.collection(collectionName).doc('placeholder').set({
  //     'listName': collectionName,
  //     'note': note ?? '',
  //     'createdAt': FieldValue.serverTimestamp(),
  //   });
  // }