// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaqlk--ay5OnpfyimOo_VYZXElIGnPZ_4',
    appId: '1:158459754417:web:d959756209319d4ea2ef90',
    messagingSenderId: '158459754417',
    projectId: 'collaborative-list-app',
    authDomain: 'collaborative-list-app.firebaseapp.com',
    storageBucket: 'collaborative-list-app.firebasestorage.app',
    measurementId: 'G-RJRXM3MK4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdAzrUGDSOSCWC3gqVn19CZyxmQubKbG0',
    appId: '1:158459754417:android:25668456d3cce200a2ef90',
    messagingSenderId: '158459754417',
    projectId: 'collaborative-list-app',
    storageBucket: 'collaborative-list-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSz6O9-H6IqmY1g34rplGT4Cpge-xWVrI',
    appId: '1:158459754417:ios:78cfd5f07dbcef59a2ef90',
    messagingSenderId: '158459754417',
    projectId: 'collaborative-list-app',
    storageBucket: 'collaborative-list-app.firebasestorage.app',
    iosBundleId: 'com.example.n',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSz6O9-H6IqmY1g34rplGT4Cpge-xWVrI',
    appId: '1:158459754417:ios:78cfd5f07dbcef59a2ef90',
    messagingSenderId: '158459754417',
    projectId: 'collaborative-list-app',
    storageBucket: 'collaborative-list-app.firebasestorage.app',
    iosBundleId: 'com.example.n',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaqlk--ay5OnpfyimOo_VYZXElIGnPZ_4',
    appId: '1:158459754417:web:f3a57dc846703eaea2ef90',
    messagingSenderId: '158459754417',
    projectId: 'collaborative-list-app',
    authDomain: 'collaborative-list-app.firebaseapp.com',
    storageBucket: 'collaborative-list-app.firebasestorage.app',
    measurementId: 'G-JSV5QJ7NEZ',
  );
}
